name: Deploy docusaurus

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Setup SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Sync files to server
        run: |
          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/docusaurus

      - name: Build Docker and restart container
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/${{ secrets.VPS_USER }}/docusaurus &&
            docker build -t docusaurus:latest . &&
            docker stop docusaurus || true &&
            docker rm docusaurus || true &&
            docker run -d --restart unless-stopped -p 80:80 --name docusaurus docusaurus:latest
          "
