name: Deploy Docusaurus with Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docusaurus:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docusaurus:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy on VPS
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/docusaurus:latest &&
            docker stop docusaurus || true &&
            docker rm docusaurus || true &&
            docker run -d --restart unless-stopped -p 80:80 --name docusaurus ${{ secrets.DOCKERHUB_USERNAME }}/docusaurus:latest
          "
